platform:ios, '7.0'
inhibit_all_warnings!

pod 'MKNetworkKit', :head
pod 'ECSlidingViewController'
pod 'CCHMapClusterController'
pod 'JTSImageViewController'
pod 'TOWebViewController'
pod 'GoogleAnalytics-iOS-SDK'

target :neerbyyTests, :exclusive => true do
    pod 'Kiwi/XCTest'
end
