platform:ios, '7.0'
inhibit_all_warnings!

pod 'MKNetworkKit', :head
pod 'ECSlidingViewController'
pod 'CCHMapClusterController'

target :neerbyyTests, :exclusive => true do
    pod 'Kiwi/XCTest'
end
